# When a List Is Not the Answer

## 1. Arrays

In [1]:
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.5776588394765231

### 1.1 Saving

In [2]:
filepath = open('07_floats.bin', 'wb')
floats.tofile(filepath)
filepath.close()

### 1.2 Loading

In [3]:
floats_2 = array('d')  #'d' = double-precision float => that is why it saves memory
filepath = open('07_floats.bin', 'rb')
floats_2.fromfile(filepath, 10**7)
filepath.close()

In [4]:
floats_2[-1]

0.5776588394765231

In [5]:
floats_2 == floats

True

## 2.Memory Views

In [6]:
import array

numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [7]:
memv[0]

-2

In [8]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [9]:
memv_oct[5] = 4

In [10]:
numbers

array('h', [-2, -1, 1024, 1, 2])

## 3. NumPy and SciPy

In [11]:
import numpy as np

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
type(a)

numpy.ndarray

In [13]:
a.shape

(12,)

In [14]:
a.shape = (3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a[2]

array([ 8,  9, 10, 11])

In [16]:
a[2, 1]

9

In [17]:
a[:, 1]

array([1, 5, 9])

In [18]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### 3.1 Loading

In [ ]:
import numpy as np

floats = np.loadtxt('sometext.txt')

## 4. Deques and Other Queues

In [20]:
from collections import deque

dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
dq.rotate(3)   #shift 3 steps forward
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [22]:
dq.rotate(-5)  #shift 5 steps backward
dq

deque([2, 3, 4, 5, 6, 7, 8, 9, 0, 1])

In [23]:
dq.appendleft(-1)
dq

deque([-1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [24]:
dq.extend([11, 22, 33])
dq

deque([4, 5, 6, 7, 8, 9, 0, 11, 22, 33])

In [25]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 4, 5, 6, 7, 8, 9])